### PR TITLE
doc: fix typo

### PR DESCRIPTION
**Pull request by maximivanov**
Fixing a little typo in JWT.verify method description.

### CODE REVIEW

**Comment by panva** [comment]
Hi @maximivanov

It’s [not](https://github.com/panva/jose/blob/v1.25.0/lib/jwt/verify.js#L16) a typo.

**Comment by maximivanov** [comment]
Oh I see. I'm confused by `JWT.AccessToken.verify` description though:

> A shorthand for JWT.verify with the profile option set to access_token.

**Comment by panva** [comment]
Right, well, you can fix that ;)

**Comment by panva** [comment]
Thank you

**Pull request merged**
