### PR TITLE
Pr/cloudflare worker jwks fetch

### PR DESCRIPTION
**Pull request by OwenDelahoy**
Sorry I didn't realize github actions would close my previous PR #255  

Based on your feeback I created an alternative which detects whether it's running in cloudflare workers and adjusts the fetch options based on this.

> const isCloudflareWorker = ("mode" in new Request(""))

I have tested this inside cloudflare workers and it works as expected.

### CODE REVIEW

**Comment by panva** [comment]
I've created a fix and released it already https://github.com/panva/jose/releases/tag/v3.15.5

**Comment by OwenDelahoy** [comment]
I am disappointed that after the hours I spent tracking down this bug and submitting a PR, adjusting it based on your feedback, It was not included.

I am unlikely to attempt contributing again.

**Comment by panva** [comment]
My apologies. Nevertheless thank you again for bringing the issue out and your suggestions.

**Comment by panva** [comment]
I also ask potential contributors to discuss proposals upfront.

See CONTRIBUTING.md

> When contributing to this project, please first discuss the change you wish to make via a discussion, email, or any other appropriate method with the owners of this project before proposing a change via a Pull Request.

**Pull request closed without merging**
