### PR TITLE
Fixing jest TextEncoder is not defined

### PR DESCRIPTION
**Pull request by lukasa1993**
workarounds from https://github.com/panva/jose/issues/307#issuecomment-962980133 here didn't work so if you could please take a look in my testings this helps

### CODE REVIEW

**Comment by panva** [comment]
Hi @lukasa1993 

This is only hiding the issue in one jest "environment".

Why the maintainers of those jest environment configs don't follow the standard global objects in their respective environments is unknown to me. It is also not something I'm willing to work around.

If jest isn't working for you, that's a problem of jest or the used jest environment, not individual packages that simply use known globals.

**Comment by lukasa1993** [comment]
> Hi @lukasa1993 
> 
> 
> 
> This is only hiding the issue in one jest "environment".
> 
> 
> 
> Why the maintainers of those jest environment configs don't follow the standard global objects in their respective environments is unknown to me. It is also not something I'm willing to work around.
> 
> 
> 
> If jest isn't working for you, that's a problem of jest or the used jest environment, not individual packages that simply use known globals.

yes i totally agree i just hoped this wouldn't hurt this package i cant move away from jest right now

**Comment by panva** [comment]
What runtime do you use? You're fixing the node one so why don't you use the runtime that is known to work around the many jest issues? https://www.npmjs.com/package/jest-environment-node-single-context

**Comment by lukasa1993** [comment]
> What runtime do you use? You're fixing the node one so why don't you use the environment that is known to work around the many jest issues? https://www.npmjs.com/package/jest-environment-node-single-context
> 
> 
> 
> https://backend.cafe/should-you-use-jest-as-a-testing-library

i tried that but didn't help, my runtime is mix of node and jsdoc

**Comment by panva** [comment]
> yes i totally agree i just hoped this wouldn't hurt this package i cant move away from jest right now

It doesn't hurt per se, it just doesn't strike me as something that needs to be done. For node there is `jest-environment-node-single-context` which is known to settle the jest issues. For jsdom there's https://github.com/jsdom/jsdom/issues/2524. In your case, you probably want a combination of the two because of your particular needs.

**Comment by iwasrobbed** [comment]
Fwiw, you can work around this by injecting the globals into the jest config file instead

```
import util from 'util';

const config = {
  /* ... other config here */
  globals: {
    TextEncoder: util.TextEncoder,
    TextDecoder: util.TextDecoder,
  },
};
```

inspired by https://stackoverflow.com/a/75939102/308315

Unrelated, but I also had to add `moduleNameMapper:{"^jose$": "jose"},` otherwise it was choking on an `export` at the module level

**Comment by lukasa1993** [comment]
> Fwiw, you can work around this by injecting the globals into the jest config file instead
> 
> 
> 
> ```
> 
> import util from 'util';
> 
> 
> 
> const config = {
> 
>   /* ... other config here */
> 
>   globals: {
> 
>     TextEncoder: util.TextEncoder,
> 
>     TextDecoder: util.TextDecoder,
> 
>   },
> 
> };
> 
> ```
> 
> 
> 
> inspired by https://stackoverflow.com/a/75939102/308315
> 
> 
> 
> Unrelated, but I also had to add `moduleNameMapper:{"^jose$": "jose"},` otherwise it was choking on an `export` at the module level

thanks for suggesting in my use case it still didn't work  i am just using patch package with my fix

**Pull request closed without merging**
