### PR TITLE
feat: add ESM entrypoint

### PR DESCRIPTION
**Pull request by GalacticHypernova**
As a first step towards making the package fully tree-shakable, this adds the ESM entrypoint to the package

### CODE REVIEW

**Comment by panva** [comment]
Can you point me to docs for this change, which runtime/bundler requires module that does not yet support [exports](https://github.com/panva/jose/blob/v5.6.2/package.json#L77-L109).

**Comment by GalacticHypernova** [comment]
Since the root package.json doesn't specify "type": "module" all the code under is treated as CJS by default, which is why this package is not yet tree-shakable. I doubt this can be specified as "type": "module" for compatibility purposes, but by adding a module entrypoints it will allows all code to be treated as ESM

**Comment by panva** [comment]
@GalacticHypernova I'm going to need a minimal reproduction project to confirm the before and after behaviours. The closest package.json to all ESM entrypoints does contain `"type": "module"` which ought to be enough.

**Comment by GalacticHypernova** [comment]
That's gonna be a bit challenging 😅 
Do you mind pointing me to the package.json files? I can only see the root one along with package-lock.json

I'll keep this PR as draft for now until I manage to make the repro

**Comment by panva** [comment]
> That's gonna be a bit challenging 😅 

Why?

> Do you mind pointing me to the package.json files? I can only see the root one along with package-lock.json

They're in the `dist` folder in npm as well as in git on tagged commits, i.e. https://github.com/panva/jose/tree/v5.6.2/dist/node/esm

**Comment by GalacticHypernova** [comment]
> Why?

Because the test involves some additional tools, in addition to manual practical testing due to the limitation of type definitions (you can't know which context the specific thing you're using is in, ESM or CJS).

Take a look for example at https://bundlephobia.com/package/jose@5.6.2
Notice how there is "tree-shakable" tag; I believe that's because it's trying to run it in a CJS context to see if it still picks up on it, but since the package.json doesn't specify the ESM entrypoint, it doesn't read it because of the priority differences

**Comment by panva** [comment]
I'm don't trust bundlephobia given its out of date nature. If there's a repro project set to compile/bundle/shake to ESM that can't tree shake I'll look into it. But that's the repro case i'm asking for.

**Comment by GalacticHypernova** [comment]
That's fair, I can try to make a repro project, it would just take me a bit of time to set it up correctly and make sure it's running accurately

**Comment by panva** [comment]
Bundlephobia only looks at the module's root package.json [for three indicators](https://github.com/pastelsky/package-build-stats/blob/079865c887f08ee21a1b8661202520a49c495fd5/src/getPackageStats.ts#L34-L36), actual bundlers however resolve the imported module through much more complicated means than just looking at "module" or "main", e.g. they resolve the runtime that is being targetted. That's what [`exports`](https://github.com/panva/jose/blob/v5.6.2/package.json#L77-L108) is for. When an entrypoint is determined the bundlers traverse the structure back up until they're at root again and if they encounter a [package.json with a "type"](https://github.com/panva/jose/blob/v5.6.2/dist/node/esm/package.json) property, that tells them the type of the module used (CJS, or ESM). That is unless the file extension, e.g. `.mjs` already determines it.

Both webpack and esbuild are capable of tree-shaking `jose`'s ESM with the current definition.

```
➜  pg cat src/index.js        
import * as jose from 'jose'

console.log(jose.cryptoRuntime)



➜  pg npx webpack && cat dist/main.js
asset main.js 275 bytes [emitted] [minimized] (name: main)
orphan modules 134 KiB [orphan] 78 modules
./src/index.js + 66 modules 123 KiB [built] [code generated]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value.
Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/

webpack 5.92.1 compiled with 1 warning in 436 ms
(()=>{"use strict";new TextEncoder,new TextDecoder,Error,Symbol.asyncIterator;const e=crypto;let o;e.getRandomValues.bind(e),Symbol(),"undefined"!=typeof navigator&&navigator.userAgent?.startsWith?.("Mozilla/5.0 ")||(o="jose/v5.6.2"),Symbol(),console.log("WebCryptoAPI")})();%                                                                                                                                                        


➜  pg npx esbuild src/index.js       
import * as jose from "jose";
console.log(jose.cryptoRuntime);
```

From my testing webpack doesn't even care about the sideEffects field if the it determines the import is ESM.

**Comment by GalacticHypernova** [comment]
Yea, I agree with you on the exports and the side-effects fields, because I'm using jose in an ESM only context, and otherwise it wouldn't have worked at all, but I'm looking into ways to help it get tree shaken more. I suppose the PR title is a bit misleading, that's my bad

**Comment by panva** [comment]
Feel free to come back to this if you find a possible improvement. Other than heavily refactoring the code to be less dependendant on all possible algorithms being usable I can't see more venues after https://github.com/panva/jose/releases/tag/v5.6.3

**Pull request closed without merging**
