### PR TITLE
Fix RangeError in base64url.ts when encrypting large Uint8Arrays

### PR DESCRIPTION
**Pull request by codedust**
String.fromCharCode.apply causes a RangeError for large Uint8Arrays
(> ~500kB). This happens, e.g., when encrypting larger files.

See this gist to reproduce the bug (select a large file and see the
browser console):
https://gist.github.com/codedust/88c8af3b2acd782e72ffbe0c3c8bf5af

Error message in Firefox:
```
Uncaught (in promise) RangeError: too many arguments provided for a
function call (in base64url.js:8:62)
    encode http://localhost:8000/jose/runtime/base64url.js:8
    encrypt http://localhost:8000/jose/jwe/flattened/encrypt.js:143
```

Error message in Chromium:
```
Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at encode (base64url.js:8)
    at FlattenedEncrypt.encrypt (encrypt.js:143)
    at async CompactEncrypt.encrypt (encrypt.js:23)
    at async jwe_test ((index):55)
```

Solution: Apply String.fromCharCode.apply in chunks of 32768 bytes,
see https://stackoverflow.com/a/12713326

### CODE REVIEW

**Review by panva — CHANGES_REQUESTED** [review]
Thank you for coming forth with this.

Please update your PR to have CI pass and add a unit test case for the base64url file

**Comment by codedust** [comment]
I fixed some linter issues but I'm not sure how to deal with the last one:
```
Error: src/runtime/base64url.ts(12,46): error TS2345: Argument of type 'Uint8Array' is not assignable to parameter of type 'number[]'.
```

The issue could be resolved by changing the following line from
```ts
    arr.push(String.fromCharCode.apply(null, unencoded.subarray(i, i+CHUNK_SIZE)));
```
to
```ts
    arr.push(String.fromCharCode.apply(null, Array.from(unencoded.subarray(i, i+CHUNK_SIZE))));
```

However, this would significantly decrease performance.

**Comment by codedust** [comment]
Regarding the unit tests: I couldn't find any documentation about building the library and running the tests. Did I miss anything?

**Comment by panva** [comment]
There's just one problem now that I looked into the issue - the callstack size differs per browser. So even `0x8000` may fail on some, but not on others. And this number cannot be determined and can change over time.

No idea how to deal with this.

**Pull request merged**
