### PR TITLE
Jwm

### PR DESCRIPTION
**Pull request by TelegramSam**
for commentary. :)

### CODE REVIEW

**Comment by panva** [comment]
Hi @TelegramSam,

Are you expecting that this lands? I don’t think a proprietary message format is something i’ll be extending the API surface with.

**Comment by tplooker** [comment]
Hi @panva, this project is still a W.I.P however I would just like to clarify that JWM is not  proprietary, please see this [internet draft](https://tools.ietf.org/html/draft-looker-jwm-01) for more details.

JWM draws a lot of inspiration from JWT but makes different decisions around how it uses JWS and JWE that makes it more appropriate for use in secure messaging applications.

**Comment by panva** [comment]
> Hi @panva, this project is still a W.I.P however I would just like to clarify that JWM is not proprietary, please see this [internet draft](https://tools.ietf.org/html/draft-looker-jwm-01) for more details.
> 
> JWM draws a lot of inspiration from JWT but makes different decisions around how it uses JWS and JWE that makes it more appropriate for use in secure messaging applications.

> The problem is that individual internet drafts are just about as easy to post as tweets, and receive just as much vetting.  Really, until they're adopted as a working group item, they're no more authoritative than a personal blog entry.

src: https://tools.ietf.org/html/draft-abr-twitter-reply-00

Once this is dispatched to a WG and adopted, I will be happy to revisit this as part of core (when an RFC) or a plugin (when stable enough wg draft).

**Comment by panva** [comment]
Nevertheless nice work on keeping up with the docs and coding conventions of the project. I mean, really, once adopted i'm happy to guide you through making a plugin. But this can easily be a separate module for now using `jose`'s API.

**Comment by TelegramSam** [comment]
I apologize. This is not yet ready at all, and I opened the PR to the wrong repo. I'll keep working and next time I properly submit the PR, it'll be ready.

**Pull request closed without merging**
