### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by big-kahuna-burger**
* Add snyk badges into a table
* Mark deprecated versions
* Add mailto target with relevant subject

### CODE REVIEW

**Comment by panva** [comment]
@big-kahuna-burger keeping this updated requires manual effort, plus it exposes the email address to non authenticated users. I’m going to close this until there’s an automated way. 

Plus snyk is an overkill for a library with ONE dependency ;)

**Comment by big-kahuna-burger** [comment]
Never though of email thingy, good catch. 
Tho I had a semi automated script to generate it based on row template and tags list :)

**Comment by panva** [comment]
I also prefer npm's audit as it happens right as one installs. Snyk used to fill a gap in npm, nowadays its only added benefit is the automated patch and workaround application.

**Comment by big-kahuna-burger** [comment]
Do you feel that npm audit and snyk offer same audit quality? Question being, is your preferrence solely based on npm audit being executed as npm i aftermach?

**Comment by panva** [comment]
The vulnerability databases are being kept in sync (i assume) since that's the responsible thing to do.

**Pull request closed without merging**
